os: linux
dist: focal
vm:
  size: large
language: generic

services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_ORG=zencash
    - IMAGE_NAME=sc-ci-base
    - IMAGE_TAG='bionic_jdk-11_latest'
    - PROD_RELEASE_BRANCH=main

jobs:
  include:
    - name: jdk-11_latest
      env: TESTS='000'
      script:
        - source ci/setup_env.sh
        - ci/travis_keep_alive.sh
        - ci/script.sh tests

deploy:
  provider: script
  script: ci/script.sh release
  skip_cleanup: true
  on:
    tags: true
    condition: $CONTAINER_PUBLISH = true

cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/.ivy2/cache"
  - "${TRAVIS_BUILD_DIR}/.sbt"

before_cache:
- find ${TRAVIS_BUILD_DIR}/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find ${TRAVIS_BUILD_DIR}/.sbt        -name "*.lock"               -print -delete
